/**
 * Registry of static and functional Tailwind utility classes.
 *
 * Exposes registration hooks (`registerStaticUtilities`,
 * `registerFunctionalUtilityPrefixes`) so users on the bleeding edge of
 * Tailwind can extend the recognizer without forking the library.
 */

const _staticUtilities = new Set<string>([
  // Display
  "block",
  "inline-block",
  "inline",
  "flex",
  "inline-flex",
  "table",
  "inline-table",
  "table-caption",
  "table-cell",
  "table-column",
  "table-column-group",
  "table-footer-group",
  "table-header-group",
  "table-row-group",
  "table-row",
  "flow-root",
  "grid",
  "inline-grid",
  "contents",
  "list-item",
  "hidden",
  // Position
  "static",
  "fixed",
  "absolute",
  "relative",
  "sticky",
  // Visibility
  "visible",
  "invisible",
  "collapse",
  // Flexbox
  "flex-row",
  "flex-row-reverse",
  "flex-col",
  "flex-col-reverse",
  "flex-wrap",
  "flex-wrap-reverse",
  "flex-nowrap",
  "grow",
  "grow-0",
  "shrink",
  "shrink-0",
  // Grid
  "grid-flow-row",
  "grid-flow-col",
  "grid-flow-dense",
  "grid-flow-row-dense",
  "grid-flow-col-dense",
  // Alignment
  "justify-start",
  "justify-end",
  "justify-center",
  "justify-between",
  "justify-around",
  "justify-evenly",
  "justify-stretch",
  "justify-normal",
  "justify-items-start",
  "justify-items-end",
  "justify-items-center",
  "justify-items-stretch",
  "justify-self-auto",
  "justify-self-start",
  "justify-self-end",
  "justify-self-center",
  "justify-self-stretch",
  "content-start",
  "content-end",
  "content-center",
  "content-between",
  "content-around",
  "content-evenly",
  "content-baseline",
  "content-stretch",
  "content-normal",
  "items-start",
  "items-end",
  "items-center",
  "items-baseline",
  "items-stretch",
  "self-auto",
  "self-start",
  "self-end",
  "self-center",
  "self-stretch",
  "self-baseline",
  "place-content-center",
  "place-content-start",
  "place-content-end",
  "place-content-between",
  "place-content-around",
  "place-content-evenly",
  "place-content-baseline",
  "place-content-stretch",
  "place-items-start",
  "place-items-end",
  "place-items-center",
  "place-items-baseline",
  "place-items-stretch",
  "place-self-auto",
  "place-self-start",
  "place-self-end",
  "place-self-center",
  "place-self-stretch",
  // Typography
  "uppercase",
  "lowercase",
  "capitalize",
  "normal-case",
  "truncate",
  "text-ellipsis",
  "text-clip",
  "text-left",
  "text-center",
  "text-right",
  "text-justify",
  "text-start",
  "text-end",
  "underline",
  "overline",
  "line-through",
  "no-underline",
  "antialiased",
  "subpixel-antialiased",
  "italic",
  "not-italic",
  "ordinal",
  "slashed-zero",
  "lining-nums",
  "oldstyle-nums",
  "proportional-nums",
  "tabular-nums",
  "diagonal-fractions",
  "stacked-fractions",
  "normal-nums",
  // Whitespace
  "whitespace-normal",
  "whitespace-nowrap",
  "whitespace-pre",
  "whitespace-pre-line",
  "whitespace-pre-wrap",
  "whitespace-break-spaces",
  "break-normal",
  "break-words",
  "break-all",
  "break-keep",
  // Backgrounds
  "bg-fixed",
  "bg-local",
  "bg-scroll",
  "bg-clip-border",
  "bg-clip-padding",
  "bg-clip-content",
  "bg-clip-text",
  "bg-origin-border",
  "bg-origin-padding",
  "bg-origin-content",
  "bg-repeat",
  "bg-no-repeat",
  "bg-repeat-x",
  "bg-repeat-y",
  "bg-repeat-round",
  "bg-repeat-space",
  // Borders
  "border-solid",
  "border-dashed",
  "border-dotted",
  "border-double",
  "border-hidden",
  "border-none",
  "border-collapse",
  "border-separate",
  // Tables
  "table-auto",
  "table-fixed",
  "caption-top",
  "caption-bottom",
  // Transitions
  "transition",
  "transition-none",
  "transition-all",
  "transition-colors",
  "transition-opacity",
  "transition-shadow",
  "transition-transform",
  // Transforms
  "transform",
  "transform-cpu",
  "transform-gpu",
  "transform-none",
  "transform-3d", // v4 — opt into 3D context for rotate-x / translate-z / etc.
  // v4 — bare static gradient stop utility
  "via-none",
  // Animation
  "animate-none",
  "animate-spin",
  "animate-ping",
  "animate-pulse",
  "animate-bounce",
  // Cursor
  "cursor-auto",
  "cursor-default",
  "cursor-pointer",
  "cursor-wait",
  "cursor-text",
  "cursor-move",
  "cursor-help",
  "cursor-not-allowed",
  "cursor-none",
  "cursor-context-menu",
  "cursor-progress",
  "cursor-cell",
  "cursor-crosshair",
  "cursor-vertical-text",
  "cursor-alias",
  "cursor-copy",
  "cursor-no-drop",
  "cursor-grab",
  "cursor-grabbing",
  "cursor-all-scroll",
  "cursor-col-resize",
  "cursor-row-resize",
  "cursor-n-resize",
  "cursor-e-resize",
  "cursor-s-resize",
  "cursor-w-resize",
  "cursor-ne-resize",
  "cursor-nw-resize",
  "cursor-se-resize",
  "cursor-sw-resize",
  "cursor-ew-resize",
  "cursor-ns-resize",
  "cursor-nesw-resize",
  "cursor-nwse-resize",
  "cursor-zoom-in",
  "cursor-zoom-out",
  // Pointer events
  "pointer-events-none",
  "pointer-events-auto",
  // Resize
  "resize-none",
  "resize-y",
  "resize-x",
  "resize",
  // Scroll behavior
  "scroll-auto",
  "scroll-smooth",
  // Scroll snap
  "snap-start",
  "snap-end",
  "snap-center",
  "snap-align-none",
  "snap-normal",
  "snap-always",
  "snap-none",
  "snap-x",
  "snap-y",
  "snap-both",
  "snap-mandatory",
  "snap-proximity",
  // Touch action
  "touch-auto",
  "touch-none",
  "touch-pan-x",
  "touch-pan-left",
  "touch-pan-right",
  "touch-pan-y",
  "touch-pan-up",
  "touch-pan-down",
  "touch-pinch-zoom",
  "touch-manipulation",
  // User select
  "select-none",
  "select-text",
  "select-all",
  "select-auto",
  // Will change
  "will-change-auto",
  "will-change-scroll",
  "will-change-contents",
  "will-change-transform",
  // Overflow
  "overflow-auto",
  "overflow-hidden",
  "overflow-clip",
  "overflow-visible",
  "overflow-scroll",
  "overflow-x-auto",
  "overflow-y-auto",
  "overflow-x-hidden",
  "overflow-y-hidden",
  "overflow-x-clip",
  "overflow-y-clip",
  "overflow-x-visible",
  "overflow-y-visible",
  "overflow-x-scroll",
  "overflow-y-scroll",
  // Overscroll
  "overscroll-auto",
  "overscroll-contain",
  "overscroll-none",
  "overscroll-y-auto",
  "overscroll-y-contain",
  "overscroll-y-none",
  "overscroll-x-auto",
  "overscroll-x-contain",
  "overscroll-x-none",
  // Screen reader
  "sr-only",
  "not-sr-only",
  // Appearance
  "appearance-none",
  "appearance-auto",
  // List
  "list-inside",
  "list-outside",
  "list-none",
  "list-disc",
  "list-decimal",
  // Float & Clear
  "float-start",
  "float-end",
  "float-right",
  "float-left",
  "float-none",
  "clear-start",
  "clear-end",
  "clear-left",
  "clear-right",
  "clear-both",
  "clear-none",
  // Isolation
  "isolate",
  "isolation-auto",
  // Object fit
  "object-contain",
  "object-cover",
  "object-fill",
  "object-none",
  "object-scale-down",
  // Mix blend
  "mix-blend-normal",
  "mix-blend-multiply",
  "mix-blend-screen",
  "mix-blend-overlay",
  "mix-blend-darken",
  "mix-blend-lighten",
  "mix-blend-color-dodge",
  "mix-blend-color-burn",
  "mix-blend-hard-light",
  "mix-blend-soft-light",
  "mix-blend-difference",
  "mix-blend-exclusion",
  "mix-blend-hue",
  "mix-blend-saturation",
  "mix-blend-color",
  "mix-blend-luminosity",
  "mix-blend-plus-darker",
  "mix-blend-plus-lighter",
  // Background blend
  "bg-blend-normal",
  "bg-blend-multiply",
  "bg-blend-screen",
  "bg-blend-overlay",
  "bg-blend-darken",
  "bg-blend-lighten",
  "bg-blend-color-dodge",
  "bg-blend-color-burn",
  "bg-blend-hard-light",
  "bg-blend-soft-light",
  "bg-blend-difference",
  "bg-blend-exclusion",
  "bg-blend-hue",
  "bg-blend-saturation",
  "bg-blend-color",
  "bg-blend-luminosity",
  // Filter
  "filter",
  "filter-none",
  // Backdrop filter
  "backdrop-filter",
  "backdrop-filter-none",
  // Container (v4)
  "container",
  "@container",
  // Forced color adjust
  "forced-color-adjust-auto",
  "forced-color-adjust-none",
  // Accent color
  "accent-auto",
  // Caret color
  "caret-inherit",
  "caret-current",
  "caret-transparent",
  // Box decoration break
  "box-decoration-clone",
  "box-decoration-slice",
  // Box sizing
  "box-border",
  "box-content",
  // Content
  "content-none",
]);

const _functionalPrefixes = new Set<string>([
  // Spacing
  "p",
  "px",
  "py",
  "pt",
  "pr",
  "pb",
  "pl",
  "ps",
  "pe",
  "m",
  "mx",
  "my",
  "mt",
  "mr",
  "mb",
  "ml",
  "ms",
  "me",
  "space-x",
  "space-y",
  "gap",
  "gap-x",
  "gap-y",
  // Sizing
  "w",
  "min-w",
  "max-w",
  "h",
  "min-h",
  "max-h",
  "size",
  // Inset
  "inset",
  "inset-x",
  "inset-y",
  "top",
  "right",
  "bottom",
  "left",
  "start",
  "end",
  // Typography
  "text",
  "font",
  "tracking",
  "leading",
  "line-clamp",
  "indent",
  "align",
  "decoration",
  "underline-offset",
  // Colors
  "bg",
  "border",
  "border-t",
  "border-r",
  "border-b",
  "border-l",
  "border-s",
  "border-e",
  "border-x",
  "border-y",
  "outline",
  "ring",
  "ring-offset",
  "shadow",
  "accent",
  "caret",
  "fill",
  "stroke",
  "divide",
  "divide-x",
  "divide-y",
  // Gradients
  "from",
  "via",
  "to",
  "bg-gradient-to",
  // Borders
  "rounded",
  "rounded-t",
  "rounded-r",
  "rounded-b",
  "rounded-l",
  "rounded-tl",
  "rounded-tr",
  "rounded-br",
  "rounded-bl",
  "rounded-s",
  "rounded-e",
  "rounded-ss",
  "rounded-se",
  "rounded-ee",
  "rounded-es",
  // Grid/Flexbox
  "col",
  "col-span",
  "col-start",
  "col-end",
  "row",
  "row-span",
  "row-start",
  "row-end",
  "grid-cols",
  "grid-rows",
  "auto-cols",
  "auto-rows",
  "order",
  "basis",
  "flex",
  // Transforms
  "scale",
  "scale-x",
  "scale-y",
  "rotate",
  "translate-x",
  "translate-y",
  "skew-x",
  "skew-y",
  "origin",
  // Transitions
  "duration",
  "delay",
  "ease",
  // Effects
  "opacity",
  "blur",
  "brightness",
  "contrast",
  "drop-shadow",
  "grayscale",
  "hue-rotate",
  "invert",
  "saturate",
  "sepia",
  "backdrop-blur",
  "backdrop-brightness",
  "backdrop-contrast",
  "backdrop-grayscale",
  "backdrop-hue-rotate",
  "backdrop-invert",
  "backdrop-opacity",
  "backdrop-saturate",
  "backdrop-sepia",
  // Z-index
  "z",
  // Aspect ratio
  "aspect",
  // Columns
  "columns",
  // Object
  "object",
  // Scroll
  "scroll-m",
  "scroll-mx",
  "scroll-my",
  "scroll-mt",
  "scroll-mr",
  "scroll-mb",
  "scroll-ml",
  "scroll-ms",
  "scroll-me",
  "scroll-p",
  "scroll-px",
  "scroll-py",
  "scroll-pt",
  "scroll-pr",
  "scroll-pb",
  "scroll-pl",
  "scroll-ps",
  "scroll-pe",
  // List
  "list",
  // Container query (v4)
  "@",
  // Arbitrary properties
  "[",
  // ─── v4.2.0 logical-axis utilities ───────────────────────────────────────
  // Padding/margin block-start/end (logical equivalents of pt/pb/mt/mb that
  // respect writing direction). Added in tailwindcss v4.2.0.
  "pbs",
  "pbe",
  "mbs",
  "mbe",
  // Scroll padding/margin block variants (same family).
  "scroll-pbs",
  "scroll-pbe",
  "scroll-mbs",
  "scroll-mbe",
  // Border block-start/end logical sides.
  "border-bs",
  "border-be",
  // Inset block-start/end + inline-start/end logical equivalents.
  "inset-bs",
  "inset-be",
  "inset-s",
  "inset-e",
  // Inline-axis / block-axis sizing (logical equivalents of width/height
  // for vertical writing modes).
  "inline",
  "block",
  "min-inline",
  "max-inline",
  "min-block",
  "max-block",
  // ─── v4.2.0 font-features ────────────────────────────────────────────────
  // Maps to CSS font-feature-settings — unblocks ligatures + contextual
  // alternates as Tailwind utilities.
  "font-features",
  // ─── v4 new gradient families (renamed from bg-gradient-* in v4) ─────────
  "bg-linear",
  "bg-radial",
  "bg-conic",
  // ─── 3D transform utilities (v4) ─────────────────────────────────────────
  "rotate-x",
  "rotate-y",
  "rotate-z",
  "translate-z",
  "scale-z",
  "perspective",
  "perspective-origin",
  // ─── New utility families surfaced in v4 ────────────────────────────────
  "inset-shadow",
  "inset-ring",
  "field-sizing",
  "color-scheme",
  "font-stretch",
]);

/**
 * Static utility set (no arguments). Read access is exposed as a Set so callers
 * can use `.has()` directly.
 */
export const STATIC_UTILITIES: ReadonlySet<string> = _staticUtilities;

/**
 * Register additional static utility classes (e.g. when running against
 * a future Tailwind version that introduces new bare utilities).
 */
export function registerStaticUtilities(...classes: string[]): void {
  for (const c of classes) _staticUtilities.add(c);
}

/**
 * Functional utility prefixes (utilities that take an argument).
 */
export const FUNCTIONAL_UTILITY_PREFIXES: readonly string[] = Array.from(_functionalPrefixes);

/**
 * Register additional functional utility prefixes.
 */
export function registerFunctionalUtilityPrefixes(...prefixes: string[]): void {
  for (const p of prefixes) _functionalPrefixes.add(p);
}

/**
 * Iterate over all registered functional prefixes (always reflects the
 * current registry state, including registrations made at runtime).
 */
export function functionalUtilityPrefixes(): readonly string[] {
  return Array.from(_functionalPrefixes);
}
